[package]
name = "latte"
version = "0.2.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.71"
itertools = "0.10.5"
rand = "0.8.5"
rayon = "1.7.0"

[dev-dependencies]

[lib]
name = "yeet"
path = "src/lib.rs"
